name: CICD
on:
  pull_request:
    branches:
      - develop
  push: 
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: setup node environemnt
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: install the dependencies
        run: npm ci
      - name: code coverage
        env:
          CI: true
        run: npm run test -- --coverage
      - name: Build the app
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to dev
        run: npx surge --project ./build --domain http://unarmed-house1112.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}