name: CICD
on:
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: setup node environemnt
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: install the dependencies
        run: npm ci
      - name: code coverage
        env:
          CI: true
        run: npm run test -- --coverage